[package]
name = "libnotcurses-sys"
version = "1.6.15"
authors = ["nick black <dankamongmen@gmail.com>"]
license = "Apache-2.0"
edition = "2018"
description = "Low-level Rust bindings for the notcurses C library."
repository = "https://github.com/dankamongmen/notcurses"
homepage = "https://nick-black.com/dankwiki/index.php/Notcurses"
links = "notcurses"
build = "build/build.rs"
categories = [
	"external-ffi-bindings",
	"command-line-interface",
	"visualization",
	"multimedia",
	"rendering",
	]
keywords = ["tui", "cli", "terminal", "ncurses", "ffi"]

[dependencies]
libc = {version = "0.2.74", default-features = false}
cty = "0.2.1"
cstr_core = "0.2.1"
libc-print = "0.1.13"

[build-dependencies]
bindgen = ">= 0.52.0"
cc = "1.0"
pkg-config = "0.3.18"

[dev-dependencies]
serial_test = ">= 0.4.0"
serial_test_derive = ">= 0.4.0"

[lib]
doctest = false
